#!/bin/bash

username=$1

usage="Usage: new [username]"
regex_username=^[0-9a-z_]+$

if [[ ! $username =~ $regex_username ]]; then
    echo $usage
    exit
fi

id -u $username > /dev/null 2>&1
user_exists=$?

if [ $user_exists -eq 0 ]; then
    echo "Error: user exists"
    exit
fi

pass=$(pwgen)

datadir="/data"
homedir="$datadir/home/$username"
logsdir="$datadir/logs"

addgroup $username
adduser -h $homedir -G $username -s /bin/bash -S $username
adduser nginx $username
echo "$username:$pass" | chpasswd

chmod -R 750 $homedir
chown -R $username. $homedir

if [ ! -f /data/mysql/root_password ]; then
    mysqlpass=$(pwgen -cnysB 50 1)
    /usr/bin/mysqladmin -u root password "$mysqlpass"
    echo "$mysqlpass" > /data/mysql/root_password
    chmod 400 /data/mysql/root_password
fi

echo "CREATE DATABASE $username; CREATE USER '$username'@'localhost' IDENTIFIED BY '$pass'; GRANT ALL PRIVILEGES ON $username.* TO '$username'@'localhost' ; FLUSH PRIVILEGES;" | mysql -u root --password=$(cat /data/mysql/root_password)
echo "CREATE DATABASE $username\_test; GRANT ALL PRIVILEGES ON $username\_test.* TO '$username'@'localhost' ; FLUSH PRIVILEGES;" | mysql -u root --password=$(cat /data/mysql/root_password)

supervisorctl restart php-fpm7
supervisorctl restart nginx

echo -e "----------------------"
echo -e "Username: $username"
echo -e "Password: $pass"

send-router-domains
